refactor method to compile tapechecksum
now it's relative to folder and discovers any file that needs a checksum (not covered in checksum.md5) and reports on files missing from collected checksum.md5

diff --git a/collectionchecksum b/collectionchecksum
--- a/collectionchecksum
+++ b/collectionchecksum
@@ -46,26 +46,51 @@ _maketemp(){
 while [ "${*}" != "" ] ; do
     INPUT="${1}"
     TAPECHECKSUMFILE="${INPUT}/tapechecksum.md5"
+    TEMP_CHECKSUM_COMPILATION="$(_maketemp)"
     if [ -f "${TAPECHECKSUMFILE}" ] ; then
         _report -wt "A collection checksum already exists at ${TAPECHECKSUMFILE}"
         exit 1
     fi
-    TEMPCHECKSUMFILE=$(_maketemp)
-    cd "${INPUT}"
+    _report -d -n "Concatenating existing checksum.md5 files ... "
+    find "${INPUT}" -type f -name checksum.md5 | while read CHECKSUM_FILE ; do
+        UPF="$(basename "$(dirname "${CHECKSUM_FILE}")")"
+        if [[ "${UPF}" == "metadata" ]] ; then
+            PATH_CLEANING="$(basename "$(dirname "$(dirname "${CHECKSUM_FILE}")")")/objects/"
+        else
+            PATH_CLEANING="$(echo "${CHECKSUM_FILE}" | sed "s|${INPUT}/||g;s|checksum.md5||g")"
+        fi
+        sed "s|  ./|  ./${PATH_CLEANING}|g" "${CHECKSUM_FILE}"
+    done > "${TEMP_CHECKSUM_COMPILATION}"
+    _report -d "$(wc -l "${TEMP_CHECKSUM_COMPILATION}" | awk '{print $1}') checksum.md5 were gathered for ${INPUT}."
 
-    #loop through the directories, find the checksum files, cat them together, and also sed to add the media ids
-    while read CHECKSUMFILES ; do
-        PACKAGE="$(basename "$(dirname "$(dirname "${CHECKSUMFILES}")")")"
-        _report -d "Concatenating ${CHECKSUMFILES}."
-        cat "${CHECKSUMFILES}" | sed "s|  ./|  ./${PACKAGE}/objects/|g" >> "${TEMPCHECKSUMFILE}"
-    done < <(find "${INPUT}" -maxdepth 3 -mindepth 3 -type f -iname "checksum.md5")
+    if [[ -d "${INPUT}" ]] ; then
+        cd "${INPUT}"
+        TEMP_FILE_LIST="$(_maketemp)"
+        TEMP_LIST2MD5="$(_maketemp)"
+        find . -type f ! -name ".DS_Store" > "${TEMP_FILE_LIST}"
+        LIST_COMPARE="$(diff <(cut -c 35- "${TEMP_CHECKSUM_COMPILATION}" | sort) <(sort "${TEMP_FILE_LIST}"))"
+        MISSING_FILES="$(echo "${LIST_COMPARE}" | grep "^<")"
+        echo "${LIST_COMPARE}" | grep "^>" | cut -c 3- > "${TEMP_LIST2MD5}"
+        if [[ -n "${MISSING_FILES}" ]] ; then
+            _report -w "Warning there are files that are in the checksum.md5 files but not present"
+            echo "${MISSING_FILES}"
+            exit 1
+        fi
+        TEMP_NEWMD5S="$(_maketemp)"
+        if [[ -s "${TEMP_LIST2MD5}" ]] ; then
+            _report -d "For the tape checksum, these $(wc -l "${TEMP_LIST2MD5}" | awk '{print $1}') additional files must be checksummed"
+            cat "${TEMP_LIST2MD5}"
+            md5deep -rel -f "${TEMP_LIST2MD5}" > "${TEMP_NEWMD5S}"
+            _report -d "Checksummed $(wc -l "${TEMP_CHECKSUM_COMPILATION}" | awk '{print $1}') additional files."
+        fi
+        cat "${TEMP_NEWMD5S}" "${TEMP_CHECKSUM_COMPILATION}" | sort -k2 > "${TAPECHECKSUMFILE}"
+        _report -d "${TAPECHECKSUMFILE} is ready with $(wc -l "${TAPECHECKSUMFILE}" | awk '{print $1}') checksums."
+    else
+        _report -d "${INPUT} is not a directory. Exiting."
+        exit 1
+    fi
 
-    #create md5 checksums for all of the files in the metadata directory
-    _report -d "Creating checksums for all metadata directories."
-    md5deep -rel ./*/metadata >> "${TEMPCHECKSUMFILE}"
 
-    _report -d "Sorting and saving ${TAPECHECKSUMFILE}."
-    sort -k2 "${TEMPCHECKSUMFILE}" | grep -v .DS_Store >> "${TAPECHECKSUMFILE}"
 
     shift
 done
