use local functions file rather than borrowing from mm

diff --git a/collectionchecksum b/collectionchecksum
--- a/collectionchecksum
+++ b/collectionchecksum
@@ -7,17 +7,7 @@
 # Information Package directory structure.
 
 SCRIPTDIR=$(dirname "${0}")
-
-. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ; }
-
-_maketemp(){
-    mktemp -q "/tmp/$(basename "${0}").XXXXXX"
-    if [ "${?}" -ne 0 ] ; then
-        _report -w "${0}: Can't create temp file. Exiting."
-        _writeerrorlog "_maketemp" "was unable to create the temp file, so the script had to exit."
-        exit 1
-    fi
-}
+. "${SCRIPTDIR}/ltoperfunctions" || { echo "Missing '${SCRIPTDIR}/ltoperfunctions'. Exiting." ; exit 1 ; }
 
 while [ "${*}" != "" ] ; do
     INPUT="${1}"
diff --git a/formatlto b/formatlto
--- a/formatlto
+++ b/formatlto
@@ -4,12 +4,12 @@
 # Formats an LTO tape with LTFS.
 
 SCRIPTDIR=$(dirname "${0}")
-DEPENDENCIES=(mkltfs mmfunctions)
+DEPENDENCIES=(mkltfs)
 TAPE_SERIAL_REGEX="^[A-Z0-9]{6}$"
 BLUE="$(tput setaf 4)"  # Blue     - For Questions
 NC="$(tput sgr0)"       # No Color
 
-. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ; }
+. "${SCRIPTDIR}/ltoperfunctions" || { echo "Missing '${SCRIPTDIR}/ltoperfunctions'. Exiting." ; exit 1 ; }
 
 unset VERSION
 if [[ $(dirname $(command -v "${0}")) = "/usr/local/bin" || $(dirname $(command -v "${0}")) = "${HOME}/.linuxbrew/bin" ]] ; then
diff --git a/mountlto b/mountlto
--- a/mountlto
+++ b/mountlto
@@ -3,10 +3,10 @@
 # mountlto
 
 SCRIPTDIR=$(dirname "${0}")
-DEPENDENCIES=(ltfs mmfunctions)
+DEPENDENCIES=(ltfs)
 MINIMUM_TAPE_SERIAL_LENGTH=2
 
-. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ; }
+. "${SCRIPTDIR}/ltoperfunctions" || { echo "Missing '${SCRIPTDIR}/ltoperfunctions'. Exiting." ; exit 1 ; }
 
 _cleanup_mount_dir(){
     if [[ -d "${MOUNT_DIR}" ]] ; then
diff --git a/readlto b/readlto
--- a/readlto
+++ b/readlto
@@ -9,7 +9,7 @@ TAPE_MOUNT_POINT="/Volumes"
 TAPE_SERIAL_REGEX="^[A-Z0-9]{6}$"
 TAPE_EJECT="Y"
 
-. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ; }
+. "${SCRIPTDIR}/ltoperfunctions" || { echo "Missing '${SCRIPTDIR}/ltoperfunctions'. Exiting." ; exit 1 ; }
 
 unset VERSION
 if [[ $(dirname $(command -v "${0}")) = "/usr/local/bin" || $(dirname $(command -v "${0}")) = "${HOME}/.linuxbrew/bin" ]] ; then
diff --git a/renameschemas b/renameschemas
--- a/renameschemas
+++ b/renameschemas
@@ -4,7 +4,7 @@
 
 SCRIPTDIR=$(dirname "${0}")
 
-. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ; }
+. "${SCRIPTDIR}/ltoperfunctions" || { echo "Missing '${SCRIPTDIR}/ltoperfunctions'. Exiting." ; exit 1 ; }
 
 unset VERSION
 if [[ $(dirname $(command -v "${0}")) = "/usr/local/bin" || $(dirname $(command -v "${0}")) = "${HOME}/.linuxbrew/bin" ]] ; then
