Moved usage function, fixed mountlto, unquoted OPTIND

diff --git a/formatlto b/formatlto
--- a/formatlto
+++ b/formatlto
@@ -4,7 +4,6 @@
 version="0.2"
 
 SCRIPTDIR=$(dirname "${0}")
-. "${SCRIPTDIR}/ltofunctions" || { echo "Missing '${SCRIPTDIR}/ltofunctions'. Exiting." ; exit 1 ;};
 
 _usage(){
     echo
@@ -18,6 +17,10 @@ _usage(){
     exit
 }
 
+. "${SCRIPTDIR}/ltofunctions" || { echo "Missing '${SCRIPTDIR}/ltofunctions'. Exiting." ; exit 1 ;};
+dependencies=(mkltfs)
+
+
 unset MIDDLE_OPTIONS
 while getopts ":fh" opt ; do
    case "${opt}" in
@@ -30,7 +33,7 @@ done
 
 if [ ! "${LTO_ARRAY}" ] ; then
     if [[ $(uname -s) == "Darwin" ]] ; then
-        LTO_ARRAY=($(system_profiler SPSASDataType | grep "SCSI Target Identifier" | cut -d : -f2 | xargs)) # try to figure out how many lto decks are attached
+        LTO_ARRAY=($(system_profiler SPSASDataType | grep "SCSI Target Identifier" | cut -d : -f2 | sort | xargs)) # try to figure out how many lto decks are attached
     else
         LTO_ARRAY=(0) # to do: itemize when there are multiple lto drives in Linux
     fi
diff --git a/writelto b/writelto
--- a/writelto
+++ b/writelto
@@ -6,7 +6,6 @@ TAPE_MOUNT_POINT="/Volumes"
 TAPE_SERIAL_REGEX="[A-Z0-9]\{6\}"
 LTO_LOGS="$HOME/Documents/lto_indexes"
 SCRIPTDIR=$(dirname "${0}")
-. "${SCRIPTDIR}/ltofunctions" || { echo "Missing '${SCRIPTDIR}/ltofunctions'. Exiting." ; exit 1 ;};
 
 _usage(){
     echo "writelto"
@@ -14,6 +13,8 @@ _usage(){
     echo "    -t tape serial"
     exit 1
 }
+
+. "${SCRIPTDIR}/ltofunctions" || { echo "Missing '${SCRIPTDIR}/ltofunctions'. Exiting." ; exit 1 ;};
 
 # command-line options
 OPTIND=1
@@ -24,7 +25,7 @@ while getopts ":t:" opt ; do
         :) echo "Option -${OPTARG} requires an argument" ; exit 1 ;;
     esac
 done
-shift $(( "${OPTIND}" - 1 ))
+shift $(( ${OPTIND} - 1 ))
 
 
 SOURCE_DIR="${1}"
