getopts
- check `:` before `*`
- uniform structure through the scripts

diff --git a/indexschemas b/indexschemas
--- a/indexschemas
+++ b/indexschemas
@@ -1,22 +1,28 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
+# indexschemas
+# This script makes a text file listing certain files from the ltfs schema file.
 
 LTO_LOGS="${HOME}/Documents/lto_indexes"
 
 _usage(){
+    echo 
     echo "$(basename "${0}")"
-    echo "This script makes a text file listing certain files from the ltfs schema file."
+    echo "This script makes a text file listing certain files from the ltfs schema"
+    echo "file."
     echo "Usage:"
-    echo "    -t [check schema files modified today for volume names that may need to be overwritten]"
+    echo "  -t  check schema files modified today for volume names that may need"
+    echo "      to be overwritten"
+    echo
     exit 1
 }
 
-# command-line options
 OPTIND=1
 while getopts ":t" opt ; do
     case "${opt}" in
         t) TODAYCHECK=(-mtime -24h) ;;
-        *) echo "bad option -${OPTARG}" ; usage ;;
-        :) echo "Option -${OPTARG} requires an argument" ; exit 1 ;;
+        :) echo "Error: Option -${OPTARG} requires an argument" ; exit 1 ;;
+        *) echo "Error: Bad option -${OPTARG}" ; usage ;;
     esac
 done
 shift $(( ${OPTIND} - 1 ))
