add mmfunctions to indexschemes to look up config info

diff --git a/indexschemas b/indexschemas
--- a/indexschemas
+++ b/indexschemas
@@ -3,6 +3,10 @@
 # indexschemas
 # This script makes a text file listing certain files from the ltfs schema file.
 
+SCRIPTDIR=$(dirname "${0}")
+
+. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ; }
+
 LTO_LOGS="${LTO_INDEX_DIR}"
 
 if [[ $(dirname $(which "${0}")) = "/usr/local/bin" || $(dirname $(which "${0}")) = "${HOME}/.linuxbrew/bin" ]] ; then
