exit if no mmfunctions

diff --git a/ingestcollectionchecksum b/ingestcollectionchecksum
--- a/ingestcollectionchecksum
+++ b/ingestcollectionchecksum
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 SCRIPTDIR=$(dirname $(which "${0}"))
-. "${SCRIPTDIR}/mmfunctions"
+. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ; }
 
 if [ -z "${PREMIS_NAME}" ] || [ "${PREMIS_DB}" != "Y" ] ; then
     echo "Please configure database options in mmconfig. Exiting"
