lto2filemaker: add usage and cli args

diff --git a/lto2filemaker b/lto2filemaker
--- a/lto2filemaker
+++ b/lto2filemaker
@@ -1,9 +1,33 @@
 #!/bin/bash
 # This script presumes that you've setup a filemaker database with Filemaker Server using two tables called "lto_tapes" and "lto_files" with fields according to the LTFS XML format.
 REQUIRECONFIG="Y"
+_usage(){
+    echo
+    echo "$(basename "${0}") ${VERSION}"
+    echo "This application will create a file suitable for broadcast or editing from a video file or package input with the following options."
+    echo "Dependencies: ${DEPENDENCIES[@]}"
+    echo "Usage: $(basename "${0}") [ -v ] LTFS_SCHEMA_FILE"
+    echo "  -v N (verbosity, 0 hides curl errors, default is 0)"
+    echo "  -h ( display this help )"
+    echo
+    exit
+}
+[ "${#}" = 0 ] && _usage
+
 SCRIPTDIR=$(dirname "${0}")
 . "${SCRIPTDIR}/ltofunctions" || { echo "Missing '${SCRIPTDIR}/ltofunctions'. Exiting." ; exit 1 ;};
 
+# command-line options
+OPTIND=1
+while getopts ":v:h" opt ; do
+    case "${opt}" in
+        v) VERBOSITY="${OPTARG}" ;;
+        h) _usage ;;
+        *) echo "bad option -$OPTARG" ; _usage ;;
+        :) echo "Option -$OPTARG requires an argument" ; exit 1 ;;
+    esac
+done
+shift $(( ${OPTIND} - 1 ))
 
 LTO_TAPE_TMP=$(_maketemp)
 xml sel -t -m "/ltfsindex" -o " --data-urlencode \"creator=" -v creator -o "\" --data-urlencode \"volumeuuid=" -v volumeuuid -o "\" --data-urlencode \"generationnumber=" -v generationnumber -o "\" --data-urlencode \"accesstime=" -v directory[1]/accesstime -o "\" --data-urlencode \"backuptime=" -v directory[1]/backuptime -o "\" --data-urlencode \"changetime=" -v directory[1]/changetime -o "\" --data-urlencode \"creationtime=" -v directory[1]/creationtime -o "\" --data-urlencode \"modifytime=" -v directory[1]/modifytime -o "\" --data-urlencode \"updatetime=" -v updatetime -o "\" --data-urlencode \"readonly=" -v directory[1]/readonly -o "\" --data-urlencode \"allowpolicyupdate=" -v allowpolicyupdate -o "\" --data-urlencode \"highestfileuid=" -v highestfileuid -o "\" --data-urlencode \"name=" -v directory[1]/name -o "\" --data-urlencode \"uniq=" -v directory[1]/modifytime -o "." -v directory[1]/highestfileuid -o "." -v volumeuuid -o "." -v updatetime -o "\"" -n "$1" > "${LTO_TAPE_TMP}"
