consolidated functions into ltofunctions, prefaced all functions with underscores

diff --git a/ltofunctions b/ltofunctions
--- a/ltofunctions
+++ b/ltofunctions
@@ -13,9 +13,97 @@ elif [ ! "${CONFIG}" = "Y" -a "${REQUIRECONFIG}" = "Y" ] ; then
     exit 1
 fi
 
+_maketemp(){
+    mktemp -q "/tmp/$(basename $0).XXXXXX"
+    if [ ${?} -ne 0 ]; then
+        echo "${0}: Can't create temp file, exiting..."
+        exit 1
+    fi
+}
 
+_get_iso8601(){
+    date +%FT%T
+}
 
-pashua_run() {
+_report(){
+        local RED="$(tput setaf 1)"   # Red      - For Warnings
+        local GREEN="$(tput setaf 2)" # Green    - For Declarations
+        local BLUE="$(tput setaf 4)"  # Blue     - For Questions
+        local NC="$(tput sgr0)"       # No Color
+        local color=""
+        local startmessage=""
+        local endmessage=""
+        local echoopt=""
+        OPTIND=1
+        while getopts ":qdwstn" opt; do
+            case "$opt" in
+                q) color="$BLUE" ;;                         # question mode, use color blue
+                d) color="$GREEN" ;;                        # declaration mode, use color green
+                w) color="$RED" ; log="Y";;                 # warning mode, use color red
+                s) startmessage+=([$(basename $0)] ) ;;     # prepend scriptname to the message
+                t) startmessage+=($(_get_iso8601) '- ' ) ;;     # prepend timestamp to the message
+                n) echoopt="-n" ;;                          # to avoid line breaks after echo
+            esac
+        done
+        shift $(( ${OPTIND} - 1 ))
+        message="$1"
+        echo $echoopt "${color}${startmessage[@]}${message}${NC}"
+        [ "$log" = "Y" ] && _log -w "$message"
+}
+
+_config_edit(){
+    [ -z "$1" -o -z "$2" ] && { _report -w "The config_edit function requires two arguments. Error." ; exit ;};
+    sedtemp=$(_maketemp)
+    sed "s:^$1=[^ ]*:$1=$2:" "$CONFIG_FILE" > "$sedtemp"
+    cp "$sedtemp" "$CONFIG_FILE"
+}
+
+_test_config(){
+    for directoryvariable in OUTDIR_INGESTFILE OUTDIR_INGESTXDCAM OUTDIR_PAPER AIP_STORAGE PODCASTDELIVER YOUTUBEDELIVER TMPDIR CUSTOM_LOG_DIR LTO_INDEX_DIR ; do
+        if [ -d "${!directoryvariable}" ] ; then
+            _report -d "${directoryvariable} is a valid directory"
+        else
+            _report -w "${directoryvariable} is NOT a valid directory"
+        fi
+    done
+}
+
+_add_key(){
+    key_to_add="$1"
+    grep -q "^$key_to_add=" "$CONFIG_FILE" ; grep_code="$?"
+    if [[ ! "${grep_code}" -eq "0" ]] ; then
+        _report -td "Adding NEW variable $key_to_add to $CONFIG_FILE"
+        echo "$key_to_add=" >> "$CONFIG_FILE"
+    fi
+}
+
+_cleanup(){
+    if [ -d "${mountdir}" ] ; then
+        echo calling umount
+        umount "${mountdir}"
+        rmdir "${mountdir}"
+    fi
+}
+
+_version_schema(){
+    schemafile="$LTOLOGS/${TAPE_SERIAL}.schema"
+    if [ -f "${schemafile}" ] ; then
+        echo "${GREEN}Creating a new version of the ltfs schema file.${NC}"
+        LASTSCHEMA="${schemafile%.*}_$(stat -t '%Y%m%d-%H%M%S' -l "${schemafile}" | awk '{print $6}').schema"
+        mv -v "${schemafile}" "${LASTSCHEMA}"
+        echo "${GREEN}$(basename ${0}): schema file is versioned - ${schemafile} -> ${LASTSCHEMA}.${NC}"
+    fi
+}
+
+_checkdir(){
+if [[ ! -d "${1}" ]] ; then
+    echo "${1}" is not a directory.
+    usage
+    exit 1
+fi
+}
+
+_pashua_run() {
     # Wrapper function for interfacing to Pashua. Written by Carsten
     # Bluem <carsten@bluem.net> in 10/2003, modified in 12/2003 (including
     # a code snippet contributed by Tor Sigurdsson), 08/2004 and 12/2004.
@@ -43,7 +131,7 @@ pashua_run() {
             if [[ "${pashuainstall}" != "Y" ]] ; then
                 brew cask install pashua
                 pashuainstall="Y"
-                pashua_run
+                _pashua_run
             else
                 break 2
             fi
diff --git a/ltoperconfig b/ltoperconfig
--- a/ltoperconfig
+++ b/ltoperconfig
@@ -5,73 +5,11 @@ CONFIG="Y"
 CONFIG_VERSION="1.0"
 SCRIPTDIR=$(dirname "$0")
 CONFIG_FILE="${SCRIPTDIR}/ltoper.conf"
+SCRIPTDIR=$(dirname "${0}")
+. "${SCRIPTDIR}/ltofunctions" || { echo "Missing '${SCRIPTDIR}/ltofunctions'. Exiting." ; exit 1 ;};
 
 # local variables
 REQUIRED_VARIABLES=("FILEMAKER_USER" "FILEMAKER_PASS" "FILEMAKER_DB" "FILEMAKER_XML_URL")
-
-get_iso8601(){
-    date +%FT%T
-}
-
-maketemp(){
-    mktemp -q "/tmp/$(basename $0).XXXXXX"
-    if [ ${?} -ne 0 ]; then
-        echo "${0}: Can't create temp file, exiting..."
-        exit 1
-    fi
-}
-
-report(){
-        local RED="$(tput setaf 1)"   # Red      - For Warnings
-        local GREEN="$(tput setaf 2)" # Green    - For Declarations
-        local BLUE="$(tput setaf 4)"  # Blue     - For Questions
-        local NC="$(tput sgr0)"       # No Color
-        local color=""
-        local startmessage=""
-        local endmessage=""
-        local echoopt=""
-        OPTIND=1
-        while getopts ":qdwstn" opt; do
-            case "$opt" in
-                q) color="$BLUE" ;;                         # question mode, use color blue
-                d) color="$GREEN" ;;                        # declaration mode, use color green
-                w) color="$RED" ; log="Y";;                 # warning mode, use color red
-                s) startmessage+=([$(basename $0)] ) ;;     # prepend scriptname to the message
-                t) startmessage+=($(get_iso8601) '- ' ) ;;     # prepend timestamp to the message
-                n) echoopt="-n" ;;                          # to avoid line breaks after echo
-            esac
-        done
-        shift $(( ${OPTIND} - 1 ))
-        message="$1"
-        echo $echoopt "${color}${startmessage[@]}${message}${NC}"
-        [ "$log" = "Y" ] && _log -w "$message"
-}
-
-config_edit(){
-    [ -z "$1" -o -z "$2" ] && { report -w "The config_edit function requires two arguments. Error." ; exit ;};
-    sedtemp=$(maketemp)
-    sed "s:^$1=[^ ]*:$1=$2:" "$CONFIG_FILE" > "$sedtemp"
-    cp "$sedtemp" "$CONFIG_FILE"
-}
-
-test_config(){
-    for directoryvariable in OUTDIR_INGESTFILE OUTDIR_INGESTXDCAM OUTDIR_PAPER AIP_STORAGE PODCASTDELIVER YOUTUBEDELIVER TMPDIR CUSTOM_LOG_DIR LTO_INDEX_DIR ; do
-        if [ -d "${!directoryvariable}" ] ; then
-            report -d "${directoryvariable} is a valid directory"
-        else
-            report -w "${directoryvariable} is NOT a valid directory"
-        fi
-    done
-}
-
-add_key(){
-    key_to_add="$1"
-    grep -q "^$key_to_add=" "$CONFIG_FILE" ; grep_code="$?"
-    if [[ ! "${grep_code}" -eq "0" ]] ; then
-        report -td "Adding NEW variable $key_to_add to $CONFIG_FILE"
-        echo "$key_to_add=" >> "$CONFIG_FILE"
-    fi
-}
 
 # set up configuration file if required
 if [[ ! -f "$CONFIG_FILE" ]] ; then
@@ -81,17 +19,17 @@ if [[ ! -f "$CONFIG_FILE" ]] ; then
     echo "CONFIG_FILE_VERSION=$CONFIG_VERSION" >> "$CONFIG_FILE"
 fi
 for KEY in "${REQUIRED_VARIABLES[@]}" ; do
-    add_key "$KEY"
+    _add_key "$KEY"
 done
 
-report -d "Table of existing variables:"
+_report -d "Table of existing variables:"
 for KEY in "${REQUIRED_VARIABLES[@]}" ; do
     VALUE=$(grep "^$KEY=" "$CONFIG_FILE" | cut -d= -f2)
     printf '\t%-40s %-40s\n' "$KEY" "$VALUE"
 done
 while true ; do
     EDITOPTION="Edit config file in nano"
-    report -q "Edit a variable? "
+    _report -q "Edit a variable? "
     PS3="Selection (enter by number)? "
     select CONFIG_KEY in "$EDITOPTION" "${REQUIRED_VARIABLES[@]}" "Quit"
     do
@@ -102,5 +40,5 @@ while true ; do
     echo -n "Enter the value for $CONFIG_KEY: "
     read "CONFIG_VALUE"
     echo "$CONFIG_KEY is now set to $CONFIG_VALUE"
-    config_edit "$CONFIG_KEY" "$CONFIG_VALUE"
+    _config_edit "$CONFIG_KEY" "$CONFIG_VALUE"
 done
