movement of ltofunctions to mmfunctions, inclusion of migrate files script

diff --git a/ltoperconfig b/ltoperconfig
--- a/ltoperconfig
+++ b/ltoperconfig
@@ -4,14 +4,14 @@
 CONFIG="Y"
 CONFIG_VERSION="1.0"
 SCRIPTDIR=$(dirname "$0")
-CONFIG_FILE="${SCRIPTDIR}/ltoper.conf"
+LTO_CONFIG_FILE="${SCRIPTDIR}/ltoper.conf"
 SCRIPTDIR=$(dirname "${0}")
-. "${SCRIPTDIR}/ltofunctions" || { echo "Missing '${SCRIPTDIR}/ltofunctions'. Exiting." ; exit 1 ;};
+. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};
 
-if [ -f "${CONFIG_FILE}" ] ; then
-    . "${CONFIG_FILE}"
+if [ -f "${LTO_CONFIG_FILE}" ] ; then
+    . "${LTO_CONFIG_FILE}"
 else
-    touch "${CONFIG_FILE}"
+    touch "${LTO_CONFIG_FILE}"
 fi
 
 conf="
@@ -86,24 +86,24 @@ cb.type=cancelbutton
 		echo ""
 	
 		# write config file
-		echo "#$(basename "${0}") config file" > "${CONFIG_FILE}"
-		echo  "${config_comment}" >> "${CONFIG_FILE}"
+		echo "#$(basename "${0}") config file" > "${LTO_CONFIG_FILE}"
+		echo  "${config_comment}" >> "${LTO_CONFIG_FILE}"
 
-		echo "${FILEMAKER_USER_COMMENT}" >> "${CONFIG_FILE}"
-		echo "FILEMAKER_USER=\"${FILEMAKER_USER}\"" >> "${CONFIG_FILE}"
-		echo  >> "${CONFIG_FILE}"
+		echo "${FILEMAKER_USER_COMMENT}" >> "${LTO_CONFIG_FILE}"
+		echo "FILEMAKER_USER=\"${FILEMAKER_USER}\"" >> "${LTO_CONFIG_FILE}"
+		echo  >> "${LTO_CONFIG_FILE}"
 
-		echo  "${FILEMAKER_PASS_COMMENT}" >> "${CONFIG_FILE}"
-		echo "FILEMAKER_PASS=\"${FILEMAKER_PASS}\"" >> "${CONFIG_FILE}"
-		echo  >> "${CONFIG_FILE}"
+		echo  "${FILEMAKER_PASS_COMMENT}" >> "${LTO_CONFIG_FILE}"
+		echo "FILEMAKER_PASS=\"${FILEMAKER_PASS}\"" >> "${LTO_CONFIG_FILE}"
+		echo  >> "${LTO_CONFIG_FILE}"
 
-		echo  "${FILEMAKER_DB_COMMENT}" >> "${CONFIG_FILE}"
-		echo "FILEMAKER_DB=\"${FILEMAKER_DB}\"" >> "${CONFIG_FILE}"
-		echo  >> "${CONFIG_FILE}"
+		echo  "${FILEMAKER_DB_COMMENT}" >> "${LTO_CONFIG_FILE}"
+		echo "FILEMAKER_DB=\"${FILEMAKER_DB}\"" >> "${LTO_CONFIG_FILE}"
+		echo  >> "${LTO_CONFIG_FILE}"
 
-		echo  "${FILEMAKER_XML_URL_COMMENT}" >> "${CONFIG_FILE}"
-		echo "FILEMAKER_XML_URL=\"${FILEMAKER_XML_URL}\"" >> "${CONFIG_FILE}"
-		echo  >> "${CONFIG_FILE}"
+		echo  "${FILEMAKER_XML_URL_COMMENT}" >> "${LTO_CONFIG_FILE}"
+		echo "FILEMAKER_XML_URL=\"${FILEMAKER_XML_URL}\"" >> "${LTO_CONFIG_FILE}"
+		echo  >> "${LTO_CONFIG_FILE}"
 
-		. "${CONFIG_FILE}"
+		. "${LTO_CONFIG_FILE}"
 	fi
diff --git a/mountlto b/mountlto
--- a/mountlto
+++ b/mountlto
@@ -2,7 +2,7 @@
 # mountlto
 
 SCRIPTDIR=$(dirname "${0}")
-. "${SCRIPTDIR}/ltofunctions" || { echo "Missing '${SCRIPTDIR}/ltofunctions'. Exiting." ; exit 1 ;};
+. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};
 
 
 unset LTO_ARRAY
@@ -51,7 +51,7 @@ else
 fi
 echo "${GREEN}MOUNTING TAPE : THE TAPE WILL MOUNT TO THE ${RED}${MOUNT_DIR}${GREEN} FOLDER${NC}"
 echo "${GREEN}MOUNTING TAPE : AFTER MOUNT PRESS ${RED}CONTROL-C${GREEN} TO EJECT${NC}"
-trap _cleanup SIGHUP SIGINT SIGTERM
+trap _cleanup_mount_dir SIGHUP SIGINT SIGTERM
 if [ $(which ltfs_ldun) ] ; then
     ltfs_ldun load ${DECK}
 fi
diff --git a/writelto b/writelto
--- a/writelto
+++ b/writelto
@@ -14,7 +14,7 @@ _usage(){
     exit 1
 }
 
-. "${SCRIPTDIR}/ltofunctions" || { echo "Missing '${SCRIPTDIR}/ltofunctions'. Exiting." ; exit 1 ;};
+. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};
 
 # command-line options
 OPTIND=1
@@ -43,13 +43,13 @@ find "${SOURCE_DIR}/" -name '.DS_Store' -type f -delete
 
 _checkdir "${TAPE_PATH}"
 
-rsync -rtvO --progress "${SOURCE_DIR}/" "${TAPE_PATH}"
+"${SCRIPTDIR}/migratefiles" -o "${TAPE_PATH}" "${SOURCE_DIR}/"
 RSYNC_ERR_1="$?"
 HIDDEN_FILES=$(find "${TAPE_PATH}" -name ".*")
 if [[ "${HIDDEN_FILES}" ]] ; then
 	echo "Removing hidden files from tape."
 	find "${TAPE_PATH}" -name ".*" -delete
-	rsync -rtvO --progress "${SOURCE_DIR}/" "${TAPE_PATH}"
+	"${SCRIPTDIR}/migratefiles" -o "${TAPE_PATH}" "${SOURCE_DIR}/"
 	RSYNC_ERR_2="$?"
 fi
 umount "${TAPE_PATH}"
