remove dependency on mmfunctions

diff --git a/mountlto b/mountlto
--- a/mountlto
+++ b/mountlto
@@ -3,10 +3,44 @@
 # mountlto
 
 SCRIPTDIR=$(dirname "${0}")
-DEPENDENCIES=(ltfs mmfunctions)
+DEPENDENCIES=(ltfs)
+CONFIG_FILE="${SCRIPTDIR}/ltopers.conf"
 MINIMUM_TAPE_SERIAL_LENGTH=2
+DEFAULT_LTO_INDEX_DIR="${HOME}/Documents/lto_indexes"
 
-. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ; }
+if [[ -f "${CONFIG_FILE}" ]] ; then
+	. "${CONFIG_FILE}"
+fi
+
+_check_dependencies(){
+    DEPS_OK=YES
+    while [ "${*}" != "" ] ; do
+        DEPENDENCY="${1}"
+        if [ ! "$(which "${DEPENDENCY}")" ] ; then
+            _report -wt "This script requires ${DEPENDENCY} to run but it is not installed"
+            _report -wt "If you are running ubuntu or debian you might be able to install ${DEPENDENCY} with the following command"
+            _report -wt "sudo apt-get install ${DEPENDENCY}"
+            _report -wt "If you are running mac you might be able to install ${DEPENDENCY} with the following command"
+            _report -wt "brew install ${DEPENDENCY}"
+            DEPS_OK=NO
+        fi
+        shift
+    done
+    if [[ "${DEPS_OK}" = "NO" ]]; then
+        _report -wt "Unmet dependencies"
+        _report -wt "Aborting!"
+        exit 1
+    else
+        return 0
+    fi
+}
+
+_check_for_lto_index_dir(){
+	# if LTO_INDEX_DIR is set in ltopers.conf then that will be used, otherwise a default
+    if [ -z "${LTO_INDEX_DIR}" ] ; then
+        LTO_INDEX_DIR="${DEFAULT_LTO_INDEX_DIR}"
+    fi
+}
 
 _cleanup_mount_dir(){
     if [[ -d "${MOUNT_DIR}" ]] ; then
@@ -17,8 +51,43 @@ _cleanup_mount_dir(){
 }
 
 unset LTO_COUNT
+_report(){
+    local RED="$(tput setaf 1)"   # Red      - For Warnings
+    local GREEN="$(tput setaf 2)" # Green    - For Declarations
+    local BLUE="$(tput setaf 4)"  # Blue     - For Questions
+    local NC="$(tput sgr0)"       # No Color
+    local COLOR=""
+    local STARTMESSAGE=""
+    local ECHOOPT=""
+    local LOG_MESSAGE=""
+    OPTIND=1
+    while getopts ":qdwstn" OPT; do
+        case "${OPT}" in
+            q) COLOR="${BLUE}" ;;                         # question mode, use color blue
+            d) COLOR="${GREEN}" ;;                        # declaration mode, use color green
+            w) COLOR="${RED}" ;;        				  # warning mode, use color red
+            s) STARTMESSAGE+=([$(basename "${0}")] ) ;;   # prepend scriptname to the message
+            t) STARTMESSAGE+=($(_get_iso8601) '- ' ) ;;   # prepend timestamp to the message
+            n) ECHOOPT="-n" ;;                            # to avoid line breaks after echo
+        esac
+    done
+    shift $(( OPTIND - 1 ))
+    MESSAGE="${1}"
+    echo "${ECHOOPT}" "${COLOR}${STARTMESSAGE[*]}${MESSAGE}${NC}"
+}
+
+_maketemp(){
+    mktemp -q -t "$(basename "${0}")"
+    if [ "${?}" -ne 0 ]; then
+        echo "${0}: Can't create temp file, exiting..."
+        _report -w "_maketemp" "was unable to create the temp file, so the script had to exit."
+        exit 1
+    fi
+}
+
 unset LTFS_OPTIONS
 _check_for_lto_index_dir
+_check_dependencies "${DEPENDENCIES[@]}"
 LTO_LOGS="${LTO_INDEX_DIR}"
 if [[ "$(uname -s)" = "Darwin" ]] ; then
     # try to figure out how many lto decks are attached
