unifying
- add version
- for readability and maintenance use `cat` instead of multiple `echo`
- add `-h` option
- correct `_usage` instead of `usage`

diff --git a/renameschemas b/renameschemas
--- a/renameschemas
+++ b/renameschemas
@@ -3,31 +3,33 @@
 # renameschemas
 
 SCRIPTDIR=$(dirname "${0}")
+VERSION="0.9"
 
 . "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ; }
 
 _usage(){
-    echo
-    echo "$(basename "${0}")"
-    echo "Currently this script only works with in -u mode. It finds all .schema"
-    echo "LTFS indexes in the LTO_LOGS directory and renames them to use the"
-    echo "top-level file system directory name rather than the uuid. Any"
-    echo "conflicting filenames are moved to another folder if needed."
-    echo "Usage: $(basename "${0}") -u"
-    echo "  -u  change dir-named schema files to the tape uuid"
-    echo
-    exit 1
+    cat <<EOF
+$(basename "${0}") ${VERSION}
+Currently this script only works with in -u mode. It finds all .schema
+LTFS indexes in the LTO_LOGS directory and renames them to use the
+top-level file system directory name rather than the uuid. Any
+conflicting filenames are moved to another folder if needed.
+Usage: $(basename "${0}") -u
+  -u  change dir-named schema files to the tape uuid
+  -h  display this help
+EOF
 }
 
-[ "${#}" = 0 ] && _usage
+[ "${#}" = 0 ] && { _usage ; exit 1 ; }
 
 OPTIND=1
-while getopts ":un" opt ; do
+while getopts ":hun" opt ; do
     case "${opt}" in
+        h) _usage ; exit 0 ;;
         u) RENAME2UUID="Y" ;;
         n) RENAME2NAME="Y" ;;
         :) echo "Error: Option -${OPTARG} requires an argument" ; exit 1 ;;
-        *) echo "Error: Bad option -${OPTARG}" ; usage ;;
+        *) echo "Error: Bad option -${OPTARG}" ; _usage ; exit 1 ;;
     esac
 done
 shift $(( ${OPTIND} - 1 ))
