getopts
- check `:` before `*`
- uniform structure through the scripts

diff --git a/verifylto b/verifylto
--- a/verifylto
+++ b/verifylto
@@ -1,31 +1,36 @@
 #!/usr/bin/env bash
-# name: verifylto
-# description: verifylto creates a text document with a list of checksums that are generated after a readback. This is to ensure that all files transferred over correctly.
+
+# verifylto
+# This script creates a text document with a list of checksums that are
+# generated after a readback. This is to ensure that all files transferred over
+# correctly.
+
 HIDDEN_FILES=""
 TAPE_MOUNT_POINT="/Volumes"
 TAPE_SERIAL_REGEX="[A-Z0-9]\{6\}"
-LTO_LOGS="$HOME/Documents/lto_indexes"
+LTO_LOGS="${HOME}/Documents/lto_indexes"
 SCRIPTDIR=$(dirname "${0}")
 TAPE_EJECT="Y"
 
+. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ; }
+
 _usage(){
-    echo "verifylto"
-    echo "Usage:"
-    echo "    -t tape serial"
-    echo "    -e [ N|Y ] (state yes or no to ejecting the tape after write, default is yes)"
-    exit 1
+    echo
+    echo "$(basename "${0}") ${VERSION}"
+    echo "Usage: $(basename "${0}") -t [-e]"
+    echo "  -t  tape serial"
+    echo "  -e  state yes (Y) or no (N) to ejecting the tape after write, default"
+    echo "      is yes"
+    echo
 }
 
-. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};
-
-# command-line options
 OPTIND=1
 while getopts ":t:e" opt ; do
     case "${opt}" in
         t) TAPE_SERIAL="${OPTARG}" ;;
         e) TAPE_EJECT="${OPTARG}" ;;
-        *) echo "bad option -${OPTARG}" ; _usage ;;
         :) echo "Option -${OPTARG} requires an argument" ; exit 1 ;;
+        *) echo "Bad option -${OPTARG}" ; _usage ; exit 1 ;;
     esac
 done
 shift $(( ${OPTIND} - 1 ))
@@ -46,5 +51,5 @@ find "${TAPE_PATH}" -type f ! -name .DS_Store -exec md5deep -rel "{}" >> "${READ
 
 case "${TAPE_EJECT}" in
     y|Y) umount "${TAPE_PATH}" ;;
-    *) echo "Done verifying but not ejecting ${TAPE_SERIAL}." ;;
+    *)   echo "Done verifying but not ejecting ${TAPE_SERIAL}." ;;
 esac
