housekeeping
- "modern" shebang
- put test if mmfunctions is there at the beginning
- cancelled never executed exit 1

diff --git a/verifylto b/verifylto
--- a/verifylto
+++ b/verifylto
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # name: verifylto
 # description: verifylto creates a text document with a list of checksums that are generated after a readback. This is to ensure that all files transferred over correctly.
 HIDDEN_FILES=""
@@ -8,6 +8,8 @@ LTO_LOGS="$HOME/Documents/lto_indexes"
 SCRIPTDIR=$(dirname "${0}")
 TAPE_EJECT="Y"
 
+. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};
+
 _usage(){
     echo "verifylto"
     echo "Usage:"
@@ -15,8 +17,6 @@ _usage(){
     echo "    -e [ N|Y ] (state yes or no to ejecting the tape after write, default is yes)"
     exit 1
 }
-
-. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};
 
 # command-line options
 OPTIND=1
@@ -30,21 +30,18 @@ while getopts ":t:e" opt ; do
 done
 shift $(( ${OPTIND} - 1 ))
 
-
 SOURCE_DIR="${1}"
 if [[ ! $(echo "${TAPE_SERIAL}" | grep "${TAPE_SERIAL_REGEX}") ]] ; then
     echo "${TAPE_SERIAL} is not valid. The tape id must be exactly 6 capital letters and/or numbers."
     _usage
-    exit 1
 fi
 
 TAPE_PATH="${TAPE_MOUNT_POINT}/${TAPE_SERIAL}"
-
 _checkdir "${TAPE_PATH}"
 
 VERIFYTIME=$(_get_iso8601_c)
 READBACKDIR="${LTO_LOGS}/readback_checksums"
-_mkdir2  "${READBACKDIR}"
+_mkdir2 "${READBACKDIR}"
 find "${TAPE_PATH}" -type f ! -name .DS_Store -exec md5deep -rel "{}" >> "${READBACKDIR}/${TAPE_SERIAL}_ReadBack_checksum_${VERIFYTIME}.md5" \;
 
 case "${TAPE_EJECT}" in
